// ----------------------------------------------------------------------
// -- COURSE SETTINGS:
// ----------------------------------------------------------------------
// -- NOTE: Do not edit this file unless you are a WDS team member.
// -- ABOUT: This file loads all libraries and creates each page.
// -- AUTHOR: Mike Jarrell - WDS
// ======================================================================

// ----------------------------------------------------------------------
// -- CDN SETTINGS
// ----------------------------------------------------------------------	
var course_location = "live"; // live, local
var core_folder = 'latest/'; // From Root - IF SET to Local this is where the core files should be
var CFVersion = 'latest';

// ----------------------------------------------------------------------
// -- INCLUDED FILES
// ----------------------------------------------------------------------
// -- String Array
// -- example: '../global/js/jslibs.js',...
// ----------------------------------------------------------------------

var course_csslibs = ['../global/css/template_theme.css','../global/css/custom.css','../global/css/media_queries.css','../global/css/menu.css'];
var course_jslibs = ['../global/js/course.js'];

var ie_csslibs = [];
var ie_jslibs = [];

// ----------------------------------------------------------------------
// -- GENERAL COURSE SETTINGS
// ----------------------------------------------------------------------
var settings = {}; // do not edit
var show = {}; // do not edit
var external = {}; // do not edit

settings['course_title'] = 'AP Calculus BC';
settings['link_glossary'] = '';
settings['link_notes'] = '';
settings['use_local_language'] = false; // Uses local language file instead of global language file.
settings['show_page_number_by'] = 'lesson'; //blank = default, module, lesson
settings['developers'] = ['Project Manager: Christine Dossin','Content Writer: Anastacia LaCombe','Curriculum Specialist/SME: Crystal Guiler','Web Developer: Michael Shur','Art Director: Richard Flores, Tricia Sawyer','External Reviewers: Lisa Berkson, Dorothy Schroeder','Assessment Writers Irene Payne, Lisa Ullman','Quality Assurance: Lloyd Campbell, Pat Intravichit, Steve Wolitzky'];
settings['use_mathJax'] = false;
settings['has_getting_started'] = true; // This will display the first module title in the navigation (Getting Started)

// Look & Feel
settings['uiSkin'] = '_template';
settings['meSkin'] = 'cf20';
settings['course_font'] = ''; //Google Fonts Link
settings['copyrightblock'] = false;
settings['flvs_logo_type'] = 'black'; // color, white, black
settings['home_show_title'] = true;
settings['home_popup_top_position'] = 70;
settings['home_popup_animation'] = 'fade';
settings['home_show_credits'] = true;
settings['use_templates_for_design'] = true;
//**Android fixed layout items converts to absolute positioning (position: fixed css items)
settings['layout_fixed_css'] = ''; //defaults: #headbar, #side_nav, #menu, #menua, #nav_menu

// Advanced Settings
settings['course_root'] = '../';
settings['course_home'] = '../index.htm';
settings['home_add_target'] = false;
settings['use_analytics'] = false;
settings['ua_account'] = ''; // your dedicated GoogleUA account number

// Depricated Settings from 2.x
settings['navigation_width'] = '350';

// Template Definitions are class names of elements that need to be removed from the template when on 
// small mobile devices	and external pages.	(String Array)			
var template_defs = {/*header,footer, */};

// Show / Hide Objects (true/false)									
show['notes_link'] = true;
show['glossary_link'] = false;
show['copyright_link'] = true;
show['bookmarks_link'] = true;
show['text_resize_links'] = false;
show['progress_bar'] = true;
show['developer_credit'] = true;

// ----------------------------------------------------------------------
// -- CUSTOM MENU ITEMS
// ----------------------------------------------------------------------
// -- Array Object [ Strings ]
// -- [0] = Link Title, [1] = Link, [2] = pop/modal-pop, [3] = class name for styling
// ----------------------------------------------------------------------
var custom_sidemenu_items = [
				['Resources','../global/copyright.htm','modal-pop','resource_link']
];

// ----------------------------------------------------------------------
// -- RENDER COURSE FOR 3RD PARTY
// ----------------------------------------------------------------------
external['render_for_ca'] = false; // Connections Academy
external['render_for_gs'] = false; // Global Services
external['show_flvs_copyright'] = true;

/***********************************************************************/
// ----------------------------------------------------------------------
// -- DO NOT EDIT BELOW THIS LINE
// ----------------------------------------------------------------------
/** NEW 3.0 **/

var cdn_location = "//cdn.flvsgl.com/cdn/"+ CFVersion +"/";

// FLVS Global Object
var FLVS = {
		settings:settings,
		Sitemap:'',
		ui_options : ''
	}; 

var loroot,root;
if (typeof loroot === 'undefined') { _local = '../global/'; var loroot = ''; } else { var _local = loroot; }
//location
var url = (course_location == 'local') ? loroot + '../' + core_folder : cdn_location; // url from course page
var url_root = (course_location == 'local') ? loroot + core_folder : cdn_location; // url from root

// Determine which Setup File to Use (cdn/js/setup_?.js)
var setupfile;
var isindex;
var isexternal;
var islearningobject;
var loadnothing;
var cdn_from_here; // For external files to find the root based on the defined root var;

if(isindex != true && isexternal != true && islearningobject != true && loadnothing != true) { // Makes sure that this is a course page
		setupfile = url+'js/setup_course.js';
} else if (isexternal != true && islearningobject == true) {
	//Learning Object
	var folder = 'learning_object';
	if (isindex != true) { // Makes sure that this is a course page
		setupfile = url + 'js/setup_course.js';//learning_object
	} else {
		setupfile = url_root + 'js/setup_lo_home.js';//setup
		url = url_root;//update url var
	}
} else {
	if(isindex == true){ // Checks if this is the Index Page
		setupfile = url_root+'js/setup_home.js';
		url = url_root;
	} else if(isexternal == true){ // Checks if this is an external page
		// Get URL based on Defined "Root"
		cdn_from_here = (course_location == 'local') ? root+core_folder : cdn_location;
		url = cdn_from_here;
		setupfile = cdn_from_here+'js/setup_externalpage.js';
	}
}
//===========================================================
// Content Loader - DO NOT TOUCH, UNLESS ABSOLUTELY NECESSARY
//===========================================================

//Load jQuery FAST
//===============================================================================================
window.onload = function(){
	
	importJs(url+'js/jquery-1.7.2.min.js', function() {
		//load setup file...
		if (loadnothing != true) {
			// Load the setup.js file for the appropriate page.
			importJs(url+'js/flvs_loader.js',function(){
				importJs(setupfile, function(){
					init_setup();
				});
				ilsettings();
			});
		}	
	});

}
//Hide Flickr of Static Content
if (isindex != true) {
	var initCSS = document.createElement('style');
		initCSS.type = 'text/css';
		initCSS.media = 'screen';
	document.getElementsByTagName("head")[0].appendChild(initCSS);
	if (loadnothing != true) { //avoid hiding page content (body)
		if(navigator.appName != 'Microsoft Internet Explorer' && navigator.appVersion != 8){ 
			initCSS.appendChild(document.createTextNode("body{display:none;}html,body{height:100%;}")); 
		} else {
			initCSS.styleSheet.cssText = "body{display:none;}";
		}
	}
} //index check


//=================================================================================================
// Create a new <script> and then run the init() function
function importJs(setupfile, init) {
	
	var setup = document.createElement('script');
				setup.setAttribute('type','text/javascript');
				setup.setAttribute( "src", setupfile);	
	
	if(setup.readyState){ // IE 9 <
		setup.onreadystatechange = function () {
			if(setup.readyState == 'loaded' || setup.readyState	== 'complete'){
				setup.onreadystatechange = null;
				if (init !== undefined) {
					init();
				}
			}
		}
			
	} else {
		
		setup.onload = function () {
			//alert('script loaded.');
			if (typeof init == 'function') {
				init();
			}
		}
	}
	
	document.getElementsByTagName("head")[0].appendChild(setup); //finish
} //end importJS



//Interactive Library Options Settings
function ilsettings(){var e=["blacktie","blitzer","default","eggplant","excite_bike","flickr","hotsneak","humanity","layton","lefrog","pepper","smoothness","southstreet","sunny","swanky"];var t=$.inArray(settings.uiSkin,e)>-1;var n="css/ilskin/";FLVS.ui_options=new function(){this.standalone=false;this.locPath=typeof url==="undefined"||typeof url===""?"../localpathhere/":url;this.js_path=this.locPath+"js/";this.folder=this.locPath+"js/il/";this.css_path=this.locPath+"css/";this.imgs_path="../global/images/il/";this.ill_core=this.folder+"core/";this.ill_core_plugins=this.ill_core+"plugins/";this.ill_custom_plugins=this.folder+"custom_plugins/";this.ill_skin=_local+n;this.uiSkin=settings.uiSkin==""||typeof settings.uiSkin==="undefined"||settings.uiSkin.charAt(0)!="_"&&!t?"cf2.0":settings.uiSkin;this.uiSkinPath=this.uiSkin=="cf2.0"||t||settings.uiSkin.charAt(0)!="_"?this.locPath+n+this.uiSkin:(typeof root=='undefined'?'':root)+this.ill_skin+(this.uiSkin=this.uiSkin.charAt(0)!="_"?this.uiSkin:this.uiSkin.substr(1))}}