//===========================================================
// Learning Objects Settings/ Content Loader - DO NOT TOUCH, UNLESS ABSOLUTELY NECESSARY
//===========================================================

// ----------------------------------------------------------------------
// -- LEARNING OBJECT SETTINGS:
// ----------------------------------------------------------------------
// -- NOTE: Do not edit this file unless you are a WDS team member.
// -- AUTHOR: Will Jones - WDS
// ======================================================================
//Load external libs/files here
var course_csslibs = [];//-- example: '../global/js/jslib.js','../global/js/jslib2.js'
var course_jslibs = []; //-- example: '../global/js/jslib.js','../global/js/jslib2.js'

// IMPORTANT MUST HAVES
//===========================================================

// Learning Object Sitemap (local to LO)
var sitemap = '../global/xml/sitemap.xml';

//Size of width and height (left and right nav buttons)
var navButtonSize = 35;

var islearningobject = true; // Loads LO

// location to course global root from LO folder
var loroot = '../../../';

var lo_show = {
			lo_levels : true,
			lo_breadcrumbs : true,
			lo_dropDownMenu: true,
			lo_headerNavigation : true,
			lo_footer : true
		}		
				
//Link Locations  (easy access)
//local images
var flvs_link = '../global/imgs/logo_flvs_blue.png';
var arrowLeft = '../global/imgs/left_arrow.png';
var arrowRight = '../global/imgs/right_arrow.png';

//==============================================================