// ----------------------------------------------------------------------
// -- COURSE LANGUAGE FILE:
// ----------------------------------------------------------------------
// -- NOTE: Do not edit this file unless you are a WDS team member.
// -- ABOUT: This file defines the language of the template components that displays
// -- AUTHOR: Mike Jarrell - WDS
// ======================================================================

var language = {
	
	// Headbar
	prev_link : 'Previous Page',
	next_link : 'Next Page',
	home_link : 'Course Home',
	
	// Side Navigation
	nav_link  : 'Course Navigation',
	nav_notes : 'Notes',
	nav_glossary : 'Glossary',
	nav_bookmark : 'Go To Bookmarked Page',
	nav_txtsizeplus : 'Enlarge Text',
	nav_txtsizereset : 'Reset Text',
	nav_txtsizeminus : 'Shrink Text',
	nav_sidemenu_close : 'Close',
	
	// Bookmark
	bookmark_active : 'Clear Bookmark',
	bookmark_inactive : 'Bookmark this Page',
	
	// Interactives
	Print:"Print",
	PrintPage:"Print Page",
	TextVersion:"Show Text Version",
	Interactive:"Show Interactive",
	Audio:"Show Audio Player",
	Video:"Show Video",
	
	// Footer
	copyright_title : 'Copyright Page',
	
	// For GS and CA Friends
	
	// FLVS VERBAGE
	segment_name : 'Segment',
	module_name : 'Module',
	lesson_name : 'Lesson',
	assignment_name : 'Assignment',
	course_info_area: ' Course Information Area',
	email : 'Email',
	parent_guardian: 'Parent or Guardian',
	assessment_area: 'Assessment Area',
	discussion_area: 'Discussion Area'
	
	/*
	// Uncomment and comment other blocks for different external entities
	// CA VERBAGE
	segment_name : 'Semester',
	module_name : 'Unit',
	lesson_name : 'Lesson',
	assignment_name : 'Assessment',
	course_info_area: ' Lesson Resource Packet',
	email : 'Webmail message',
	parent_guardian: 'Learning Coach',
	assessment_area: 'Assessment',
	discussion_area: 'Discussion'
	*/
	
};