// <![CDATA[
document.writeln('<div class="dc-rnav"><a href="javascript:history.go(-1)" title="Go Back">Go Back</a> | <a href="index.html" title="Back to Main Menu">Main Menu</a> | <a href="faq.html" title="Frequently Asked Questions">FAQ</a> | <a href="credits.html" title="Development Credits">[?]</a></div>');
document.writeln('<div class="header">');
document.writeln('  <div class="logo">');
document.writeln('    <h1><a href="index.html" title="Go: DreamCodes Main Menu">DreamCodes v1.25</a></h1>');
document.writeln('    HTML Template Shortcodes</div>');
document.writeln('</div>');
document.writeln('<ul id="ldd_menu" class="ldd_menu">');
document.writeln('  <li> <span>Format <img src="dc_images/arrow_down.png" align="absmiddle"></span>');
document.writeln('    <div class="ldd_submenu">');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading"><a href="index-format.html">Format Overview</a></li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="headers.html">Page Headers<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-pageheaders.jpg" style="float: left;" /><strong>Page Headers</strong><br />');
document.writeln('          Spice up your pages with these fancy title headers.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="dropcaps.html">Dropcaps<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-dropcaps.jpg" style="float: left;" /><strong>Dropcaps</strong><br />');
document.writeln('          Add letter dropcaps.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="highlighter.html">Text Highlighter<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-highlighter.jpg" style="float: left;" /><strong>Text Highlighter</strong><br />');
document.writeln('          Highlight text paragraphs or important keywords.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="spoiler_codes.html">Spoiler Codes<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-spoilers.jpg" style="float: left;" /><strong>Spoilers</strong><br />');
document.writeln('          Create movie/data spoilers easily! </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="fontstyler.html">Google Web Fonts<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-fontstyler.jpg" style="float: left;" /><strong>Google Web Fonts</strong><br />');
document.writeln('          Change your page fonts. Over 500 fonts in library.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="pullquotes.html">Pullquotes<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-pullquotes.jpg" style="float: left;" /><strong>Pullquotes</strong><br />');
document.writeln('          Create standout pullquotes.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="blockquotes.html">Blockquotes<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-blockquotes.jpg" style="float: left;" /><strong>Blockquotes</strong><br />');
document.writeln('          Create testimonials and remarks.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="comment_boxes.html">Comment Boxes<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-commentboxes.jpg" style="float: left;" /><strong>Comment Boxes</strong><br />');
document.writeln('          Create comment boxes & testimonials.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="lists.html">Lists<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-lists.jpg" style="float: left;" /><strong>Lists</strong><br />');
document.writeln('          Create fancy ordered lists with icon bullets.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading">&nbsp;</li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="datagrid.html">Data Grid<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-datagrid.jpg" style="float: left;" /><strong>Table Data Grid</strong><br />');
document.writeln('          Organize data with sortable table data grids.<br />Instant search, auto pagination, live calculation. </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="tables1.html">Table Styles I<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-tables1.jpg" style="float: left;" /><strong>Table Styles I</strong><br />');
document.writeln('          Stylish CSS table styles - various colors.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="tables2.html">Table Styles II<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-tables2.jpg" style="float: left;" /><strong>Table Styles II</strong><br />');
document.writeln('          Stylish CSS table styles - grey tones.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="image_hover_effects.html">Image Hover Effects<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-imageeffects.jpg" style="float: left;" /><strong>Image Hover Effects</strong><br />');
document.writeln('          Add hover effects to your images.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="image_captions.html">Image Captions<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-imagecaptions.jpg" style="float: left;" /><strong>Image Captions</strong><br />');
document.writeln('          Add captions to your images.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="image_frames.html">Image Frames<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-imageframes.jpg" style="float: left;" /><strong>Image Frames</strong><br />');
document.writeln('          Add stylish frame borders to your images.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="form_beautify.html">Form Beautify<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-form-beautify.jpg" style="float: left;" /><strong>Form Beautify</strong><br />');
document.writeln('          Beautify your existing forms by simply adding a few lines of code.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="divider.html">Dividers<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-divider.jpg" style="float: left;" /><strong>Dividers</strong><br />');
document.writeln('          Add line dividers/horizontal rulers.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="html-editor/index.html" target="_blank">Live HTML Editor<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-htmledit.jpg" style="float: left;" /><strong>Live HTML Editor</strong><br />');
document.writeln('          Test CSS/JS & HTML codes in real-time.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <a class="ldd_subfoot" href="index-format.html"> + View All In One Page</a> </div>');
document.writeln('  </li>');
document.writeln('  <li> <span>Embed <img src="dc_images/arrow_down.png" align="absmiddle"></span>');
document.writeln('    <div class="ldd_submenu">');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading"><a href="index-embed.html">Embed Overview</a></li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="webstore.html">Instant.WebStore<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-webstore.jpg" style="float: left;" /><strong>Instant.WebStore</strong><br />');
document.writeln('          Setup a simple ecommerce store & accept orders in just 10 minutes. No database required. 100% browser based.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="embed_videos.html">Embed Videos<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-embed-videos.jpg" style="float: left;" /><strong>Embed Videos</strong><br />');
document.writeln('          Embed YouTube, Vimeo, HTML 5, DM videos.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="embed_pdf.html">Embed PDF File<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-embed-pdf.jpg" style="float: left;" /><strong>Embed PDF File</strong><br />');
document.writeln('          Embed Adobe PDF files internally or externally on a webpage.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="social_networking.html">Social Networks<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-social-networks.jpg" style="float: left;" /><strong>Social Networks</strong><br />');
document.writeln('          Add Facebook Likes/Box, Twitter Follow, Tweet, Google+ buttons, pInterest & more!</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="tweet.html">Twitter Feeds<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-twitter-feeds.jpg" style="float: left;" /><strong>Twitter Feeds</strong><br />');
document.writeln('          Add live twitter streams to your web pages. Just copy code + enter your twitter username!</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="rssfeeds.html">RSS Feeds<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-rss-feeds.jpg" style="float: left;" /><strong>RSS Feeds</strong><br />');
document.writeln('          Display RSS Feeds on your website. Just copy code + enter a RSS URL! </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="site_screenshot.html">Site Screenshot<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-site-screenshot.jpg" style="float: left;" /><strong>Generate Site Screenshot</strong><br />');
document.writeln('          Dynamically generate a screenshot of any website URL by simply pasting some HTML codes on your webpage.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="maps.html">Bing/Google Maps<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-gps-maps.jpg" style="float: left;" /><strong>Bing/Google Maps</strong><br />');
document.writeln('          Add interactive Google Maps/Bing Maps within minutes.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="flickr.html">Flickr Gallery<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-flickr.jpg" style="float: left;" /><strong>Flickr Gallery</strong><br />');
document.writeln('          Stream photos from your flickr account to your webpage with jquery.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading">&nbsp;</li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="site_search.html">Site Search<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-sitesearch.jpg" style="float: left;" /><strong>Site Search</strong><br />');
document.writeln('          Add site search to your website. Powered by Google.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="paypal_button.html">PayPal Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-paypal-btn.jpg" style="float: left;" /><strong>PayPal Buttons</strong><br />');
document.writeln('          Accept and process credit card payments with Paypal links.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="contact_forms.html">Contact Forms<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-contactforms.jpg" style="float: left;" /><strong>Contact Forms</strong><br />');
document.writeln('          Create beautiful contact forms.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="popup_dialog.html">Popup Dialogs<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-popupdialogs.jpg" style="float: left;" /><strong>Popup Dialogs</strong><br />');
document.writeln('          Create popup jquery message dialogs.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="message_box.html">Message Boxes<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-messagebox.jpg" style="float: left;" /><strong>Message Boxes</strong><br />');
document.writeln('          Show alert/confirmation message boxes.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="lightbox.html" target="_blank">jQuery Lightbox<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-lightbox.jpg" style="float: left;" /><strong>Image Lightbox</strong><br />');
document.writeln('          Display content in popup modal dialogs with darkened background.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="inline_content.html">Inline Content<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-inline-content.jpg" style="float: left;" /><strong>Inline Content</strong><br />');
document.writeln('          Add scrollable inline HTML content windows.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="syntaxhighlighter.html">Syntax Highlighter<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-syntax-highlighter.jpg" style="float: left;" /><strong>Syntax Highlighter</strong><br />');
document.writeln('          Highlight your source code for easier viewing/source formatting. Supports HTML, CSS, Pascal, Java, JS, PHP, Python, ROR, VB, SQL, XML, C and more! </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="tooltips.html">Tooltips<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-tooltips.jpg" style="float: left;" /><strong>Tooltips</strong><br />');
document.writeln('          Add popup tooltip hints to your links, images and forms!</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <a class="ldd_subfoot" href="index-embed.html"> + View All In One Page</a> </div>');
document.writeln('  </li>');
document.writeln('  <li> <span>Organize <img src="dc_images/arrow_down.png" align="absmiddle"></span>');
document.writeln('    <div class="ldd_submenu">');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading"><a href="index-organize.html">Organize Overview</a></li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="tabs.html">Tabs<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-tabs.jpg" style="float: left;" /><strong>Tabs</strong><br />');
document.writeln('          Organize content in tabbed containers.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="columns.html">Columns<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-columns.jpg" style="float: left;" /><strong>Columns</strong><br />');
document.writeln('          Quickly add columns to your webpages.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="accordion_toggle.html">Accordions<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-accordions.jpg" style="float: left;" /><strong>Accordions</strong><br />');
document.writeln('          Organize data in tab groups that can expand/collapse. </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="toggle.html">Toggles<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-toggles.jpg" style="float: left;" /><strong>Toggles</strong><br />');
document.writeln('          Create expandable Q&A toggles. </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="pricingtables.html">Pricing Tables<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-pricingtables.jpg" style="float: left;" /><strong>Pricing Tables</strong><br />');
document.writeln('          Create stylish comparison tables.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="pagination.html">Pagination<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-pagination.jpg" style="float: left;" /><strong>Pagination</strong><br />');
document.writeln('          Create page numbers in your webpages. </span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="breadcrumbs.html">Breadcrumbs<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-breadcrumbs.jpg" style="float: left;" /><strong>Breadcrumbs</strong><br />');
document.writeln('          Create navigation aids in your webpages.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading">&nbsp;</li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="ribbons.html">Ribbons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-ribbons.jpg" style="float: left;" /><strong>Ribbons</strong><br />');
document.writeln('          Mark your images or content with ribbons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="carousel_hor.html">Horizontal Carousel<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-hcarousel.jpg" style="float: left;" /><strong>Horizontal Carousel</strong><br />');
document.writeln('          Add sliding carousels to your webpages.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="carousel_ver.html">Vertical Carousel<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-vcarousel.jpg" style="float: left;" /><strong>Vertical Carousel</strong><br />');
document.writeln('          Add sliding carousels to your webpages.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="css_shadows.html">CSS Shadows<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-cssshadows.jpg" style="float: left;" /><strong>CSS Shadows</strong><br />');
document.writeln('          Create DIV box shadows.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <a class="ldd_subfoot" href="index-organize.html"> + View All In One Page</a> </div>');
document.writeln('  </li>');
document.writeln('  <li> <span>Elements <img src="dc_images/arrow_down.png" align="absmiddle"></span>');
document.writeln('    <div class="ldd_submenu">');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading"><a href="index-elements.html">Elements Overview</a></li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="3d_buttons.html">3D Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-3d-buttons.jpg" style="float: left;" /><strong>3D Buttons</strong><br />');
document.writeln('          3D style - clickable buttons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="buttons_css3.html">CSS3 Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-css3-buttons.jpg" style="float: left;" /><strong>CSS3 Buttons</strong><br />');
document.writeln('          CSS3 style - clickable buttons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="flat_buttons.html">Flat Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-flat-buttons.jpg" style="float: left;" /><strong>Flat Buttons</strong><br />');
document.writeln('          Flat style - clickable buttons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="elite_buttons.html">Elite Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-elite-buttons.jpg" style="float: left;" /><strong>Elite Buttons</strong><br />');
document.writeln('          Multiple styles - clickable buttons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="gradient_buttons.html">Gradient Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-gradient-buttons.jpg" style="float: left;" /><strong>Gradient Buttons</strong><br />');
document.writeln('          Shaded style - clickable buttons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="text_buttons.html">Text Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-text-buttons.jpg" style="float: left;" /><strong>Text Buttons</strong><br />');
document.writeln('          Text style - clickable buttons.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="buttons_transparent.html">Transparent Buttons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-transparent-buttons.jpg" style="float: left;" /><strong>Transparent Buttons</strong><br />');
document.writeln('          See thru - clickable buttons.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading">&nbsp;</li>');
document.writeln('        <li><a class="tabref tsc_content_tooltip" href="web_icons.html"  ahref="#web_icons" rel="preview/web_icons.html">Web Icons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-web-icons.jpg" style="float: left;" /><strong>Web Icons</strong><br />');
document.writeln('          Add useful icons to your webpage.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="social_icons.html">Social Icons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-social-icons.jpg" style="float: left;" /><strong>Social Icons</strong><br />');
document.writeln('          Add social buttons to your webpage.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="payment_icons.html">Payment Icons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-payment-icons.jpg" style="float: left;" /><strong>Payment Icons</strong><br />');
document.writeln('          Display credit card acceptance logos.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="seal_icons.html">Seal Icons<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-seal-icons.jpg" style="float: left;" /><strong>Seal Icons</strong><br />');
document.writeln('          Improve conversion rates by displaying seal marks.</span></a> </li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="background_images.html" target="_blank">Background Images<span class="tsc_content_tooltip_container" style="width: 327px;"><img src="dc_images/dc-background-images.jpg" style="float: left;" /><strong>Background Images</strong><br />');
document.writeln('          Spice up your web page with new backgrounds.</span></a> </li>');
document.writeln('      </ul>');
document.writeln('      <a class="ldd_subfoot" href="index-elements.html"> + View All In One Page</a> </div>');
document.writeln('  </li>');
document.writeln('  <li> <span>Sliders <img src="dc_images/arrow_down.png" align="absmiddle"></span>');
document.writeln('    <div class="ldd_submenu">');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading"><a href="index-sliders.html">Sliders Overview</a></li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="sliders.html">Sliders One<span class="tsc_content_tooltip_container" style="width: 194px;"><img src="dc_images/dc-sliders.jpg" style="float: left;" /><strong>Banner Sliders One</strong><br />');
document.writeln('          Showcase your products using jQuery sliders.</span></a> </li>');
document.writeln('Coin Slider<br />Dream Accordion<br />Piecemaker 3D Slider<br />Ken Burns Caption Slider<br />Media Slider<br /><br />');
document.writeln('        <li><a class="tsc_content_tooltip" href="sliders2.html">Sliders Two<span class="tsc_content_tooltip_container" style="width: 194px;"><img src="dc_images/dc-sliders2.jpg" style="float: left;" /><strong>Banner Sliders Two</strong><br />');
document.writeln('          Showcase your products using jQuery sliders.</span></a> </li>');
document.writeln('Ken Burns Panel Slider<br />sCarousel Slider<br />Flick Slider<br />jFancyTile Slider<br />Skitter Slider<br /><br />');
document.writeln('        <li><a class="tsc_content_tooltip" href="sliders3.html">Sliders Three<span class="tsc_content_tooltip_container" style="width: 194px;"><img src="dc_images/dc-sliders3.jpg" style="float: left;" /><strong>Banner Sliders Three</strong><br />');
document.writeln('          Showcase your products using jQuery sliders.</span></a> </li>');
document.writeln('Nivo Slider<br />Showcase Slider<br />Broken Glass Slider<br />Touchswipe Slider<br />Panel Slider<br /><br />');
document.writeln('      </ul>');
document.writeln('      <ul>');
document.writeln('        <li class="ldd_heading">&nbsp;</li>');
document.writeln('        <li><a class="tsc_content_tooltip" href="sliders4.html">Sliders Four<span class="tsc_content_tooltip_container" style="width: 194px;"><img src="dc_images/dc-sliders4.jpg" style="float: left;" /><strong>Banner Sliders Four</strong><br />');
document.writeln('          Showcase your products using jQuery sliders.</span></a> </li>');
document.writeln('ZoomFly Slider<br />Camera Slider<br />Slidorion Slider<br />PhotoGrid Slider<br /><br />');
document.writeln('        <li><a class="tsc_content_tooltip" href="sliders5.html" target="_blank">Full Width Sliders<span class="tsc_content_tooltip_container" style="width: 248px;"><img src="dc_images/dc-sliders5.jpg" style="float: left;" /><strong>Full Width Banner Sliders</strong><br />');
document.writeln('          Showcase your products using jQuery sliders.</span></a> </li>');
document.writeln('iOS Slider<br />Parallax Slider<br />Layered Slider<br /><br />');
document.writeln('      </ul>');
document.writeln('      <a class="ldd_subfoot" href="index-sliders.html"> + View All In One Page</a> </div>');
document.writeln('  </li>');
document.writeln('</ul>');

// ]]>
